### ISSUE TITLE
module 'ikpy' has no attribute 'chain'

### ISSUE THREAD

**Issue by eEthan12138** [PaulDanielML/MuJoCo_RL_UR5#12]
When I run example.py, the following error is generated.I tried to lower the ikpy version to 3.1 and still got the error.

Traceback (most recent call last):
  File "C:/Users/eEthan1/PycharmProjects/RL_UR5/example.py", line 4, in <module>
    controller = MJ_Controller()
  File "C:\Users\eEthan1\PycharmProjects\RL_UR5\gym_grasper\controller\MujocoController.py", line 47, in __init__
    self.ee_chain = ikpy.chain.Chain.from_urdf_file(path + "/UR5+gripper/ur5_gripper.urdf")
AttributeError: module 'ikpy' has no attribute 'chain'

**Comment by eEthan12138** [comment]
I changed ikpy version into 2.3.3 ,and it works

**Comment by eEthan12138** [comment]
i have changed my ikpy version into 3.1 ,but it still dont work
