### ISSUE TITLE
Grasping_Agent_multidiscrete.py, example_agent.py errors

### ISSUE THREAD

**Issue by Scarlie23** [PaulDanielML/MuJoCo_RL_UR5#14]
Hi all, i have two errors, when i used codes. How can i solve them. Thx for informations.

python3 example_agent.py
.
.
.
EPISODE 1 STEP 1
#################################################################
Traceback (most recent call last):
  File "example_agent.py", line 27, in <module>
    observation, reward, done, _ = env.step(action, record_grasps=True)
TypeError: step() got an unexpected keyword argument 'record_grasps'

python3 Grasping_Agent_multidiscrete.py
Creating window glfw
Created new control group 'Arm'.
Created new control group 'Gripper'.
CURRENT EPSILON: 1.0
#################################################################
EPISODE 1 STEP 1
#################################################################
Traceback (most recent call last):
  File "Grasping_Agent_multidiscrete.py", line 583, in <module>
    main()
  File "Grasping_Agent_multidiscrete.py", line 545, in main
    next_state, reward, done, _ = agent.env.step(
TypeError: step() got an unexpected keyword argument 'action_info'

**Comment by digitalWriteHIGH** [comment]
I have encountered the same problem, have you solved it？
