### ISSUE TITLE
RuntimeError: Failed to initialize OpenGL

### ISSUE THREAD

**Issue by sabinakaminska95** [PaulDanielML/MuJoCo_RL_UR5#23]
Does anyone know how to solve this problem?

**(mujoco_py) xxxx@XXXX:~/.mujoco/mujoco-py/examples/MuJoCo_RL_UR5$** python3 example_agent.py
Creating window glfw
Created new control group 'Arm'.
Created new control group 'Gripper'.
Model timestep: 0.002
Set number of frames skipped:  1
dt = timestep * frame_skip:  0.002
Frames per second = 1/dt:  500
Actionspace:  MultiDiscrete([40000     6])
Observation space: Dict(rgb:Box(200, 200, 3), depth:Box(200, 200))
Found 1 GPUs for rendering. Using device 0.
Could not make EGL context current
Traceback (most recent call last):
  File "example_agent.py", line 16, in <module>
    obs = env.reset()
  File "/home/xxxx/anaconda3/envs/mujoco_py/lib/python3.8/site-packages/gym/envs/mujoco/mujoco_env.py", line 108, in reset
    ob = self.reset_model()
  File "/home/xxxx/.mujoco/mujoco-py/examples/MuJoCo_RL_UR5/gym_grasper/envs/GraspingEnv.py", line 477, in reset_model
    return self.get_observation(show=self.show_observations)
  File "/home/xxxx/.mujoco/mujoco-py/examples/MuJoCo_RL_UR5/gym_grasper/envs/GraspingEnv.py", line 398, in get_observation
    rgb, depth = self.controller.get_image_data(
  File "/home/xxxx/.mujoco/mujoco-py/examples/MuJoCo_RL_UR5/gym_grasper/controller/MujocoController.py", line 719, in get_image_data
    self.sim.render(width=width, height=height, camera_name=camera, depth=True)
  File "mjsim.pyx", line 156, in mujoco_py.cymj.MjSim.render
  File "mjsim.pyx", line 158, in mujoco_py.cymj.MjSim.render
  File "mjrendercontext.pyx", line 46, in mujoco_py.cymj.MjRenderContext.__init__
  File "mjrendercontext.pyx", line 114, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "opengl_context.pyx", line 130, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
**RuntimeError: Failed to initialize OpenGL**

**Comment by lllwin** [comment]
I met the same problem. Have you solved this?

**Comment by QWelkin** [comment]
I met the same problem. Have you solved this?

**Comment by STONEKONG** [comment]
I solved. The following two lines of code conflict with each other and cannot be implemented at the same time, which is a bug of mujoco_py.

viewer = mujoco_py.MjViewer(sim)
image = sim.render(width=300, height = 300, camera_name='cam0', depth=False)

**Comment by YINJIAJU1123** [comment]
> I solved. The following two lines of code conflict with each other and cannot be implemented at the same time, which is a bug of mujoco_py.
> 
> viewer = mujoco_py.MjViewer(sim) image = sim.render(width=300, height = 300, camera_name='cam0', depth=False)

@STONEKONG 
Hello, Stone!
I agree that the error is caused by implementing these two lines of code together. But how should we solve it. Could you please share some suggestions? 
Thank you very much.

**Comment by xyodfish** [comment]
I met the same problem. Have you solved this?

**Comment by Robby-12** [comment]
> I solved. The following two lines of code conflict with each other and cannot be implemented at the same time, which is a bug of mujoco_py.
> 
> viewer = mujoco_py.MjViewer(sim) image = sim.render(width=300, height = 300, camera_name='cam0', depth=False)

@STONEKONG
Hello, Stone!
I agree that the error is caused by implementing these two lines of code together. But how should we solve it. Could you please share some suggestions?
Thank you very much.

**Comment by chickencheng** [comment]
Using only the CPU might avoid this bug. I directly uninstalled the NVIDIA driver to solve this problem.

**Comment by TheFw** [comment]
I met the same problem. Have you solved this?Could you please share some suggestions?

**Comment by TheFw** [comment]
> I solved. The following two lines of code conflict with each other and cannot be implemented at the same time, which is a bug of mujoco_py.
> 
> viewer = mujoco_py.MjViewer(sim) image = sim.render(width=300, height = 300, camera_name='cam0', depth=False)

@STONEKONG 
Hello, Stone!
I agree that the error is caused by implementing these two lines of code together. But how should we solve it. Could you please share some suggestions?
Thank you very much.
